# dlvhdr/formulae disabled — see diffnav note below.
# tap "dlvhdr/formulae"
tap "hashicorp/tap"
tap "heroku/brew"
tap "koekeishiya/formulae"
tap "nikitabobko/tap"
tap "xcodesorg/made"
brew "as-tree"
brew "atuin"
brew "autoconf"
brew "automake"
brew "awscli"
brew "bash"
brew "bat"
brew "bun"
brew "coreutils"
brew "direnv"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "gemini-cli"
brew "gh"
brew "git-filter-repo"
brew "git-lfs"
brew "glow"
brew "gum"
brew "htop"
brew "imagemagick"
brew "jq"
brew "lazygit"
brew "mkcert"
brew "neovim"
brew "node@24"
brew "openjdk@21"
brew "pkgconf"
brew "pnpm", link: false
brew "poppler"
brew "postgresql@16"
brew "python@3.13"
brew "resvg"
brew "ripgrep"
brew "rtk"
brew "ruby"
brew "sesh"
brew "sevenzip"
brew "starship"
brew "stow"
brew "telnet"
brew "tmux"
brew "tree"
brew "uv"
brew "watchman"
brew "wget"
brew "yazi"
brew "zoxide"
brew "zsh"
brew "zsh-autosuggestions"
# diffnav formula has a broken SHA-256 (upstream source changed without a
# hash bump); disabled until dlvhdr/homebrew-formulae fixes it upstream.
# brew "dlvhdr/formulae/diffnav"
brew "koekeishiya/formulae/skhd", trusted: true
cask "1password-cli"
cask "nikitabobko/tap/aerospace", trusted: true
cask "alt-tab"
cask "android-platform-tools"
cask "android-studio"
cask "claude-code"
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-hack-nerd-font"
cask "font-symbols-only-nerd-font"
cask "gcloud-cli"
cask "ghostty"
cask "gitkraken-cli"
cask "httpie-desktop"
